/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-2:a88f70a9-3ce7-4cb4-a96f-63035308cb56",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_SC8K8S2CL",
    "aws_user_pools_web_client_id": "54va6vggd7e4uheq75rt4c3fos",
    "oauth": {
        "domain": "service-user-pool-domain-dev-cogn-test.auth.us-east-1.amazoncognito.com"
    }
};


export default awsmobile;
